# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'maindisplay.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMdiArea, QMenu,
    QMenuBar, QSizePolicy, QStatusBar, QToolBar,
    QVBoxLayout, QWidget)
import resource_rc

class Ui_MainDisplay(object):
    def setupUi(self, MainDisplay):
        if not MainDisplay.objectName():
            MainDisplay.setObjectName(u"MainDisplay")
        MainDisplay.resize(801, 621)
        self.actionNew = QAction(MainDisplay)
        self.actionNew.setObjectName(u"actionNew")
        icon = QIcon()
        icon.addFile(u":/icons/File New.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionNew.setIcon(icon)
        self.actionSave = QAction(MainDisplay)
        self.actionSave.setObjectName(u"actionSave")
        icon1 = QIcon()
        icon1.addFile(u":/icons/File Save.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave.setIcon(icon1)
        self.actionClose = QAction(MainDisplay)
        self.actionClose.setObjectName(u"actionClose")
        icon2 = QIcon()
        icon2.addFile(u":/icons/Close.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionClose.setIcon(icon2)
        self.actionExit = QAction(MainDisplay)
        self.actionExit.setObjectName(u"actionExit")
        icon3 = QIcon()
        icon3.addFile(u":/icons/Quit - Exit.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionExit.setIcon(icon3)
        self.actionUndo = QAction(MainDisplay)
        self.actionUndo.setObjectName(u"actionUndo")
        icon4 = QIcon()
        icon4.addFile(u":/icons/Undo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionUndo.setIcon(icon4)
        self.actionRedo = QAction(MainDisplay)
        self.actionRedo.setObjectName(u"actionRedo")
        icon5 = QIcon()
        icon5.addFile(u":/icons/Redo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionRedo.setIcon(icon5)
        self.actionCut = QAction(MainDisplay)
        self.actionCut.setObjectName(u"actionCut")
        icon6 = QIcon()
        icon6.addFile(u":/icons/Cut.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCut.setIcon(icon6)
        self.actionCopy = QAction(MainDisplay)
        self.actionCopy.setObjectName(u"actionCopy")
        icon7 = QIcon()
        icon7.addFile(u":/icons/Copy.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCopy.setIcon(icon7)
        self.actionPaste = QAction(MainDisplay)
        self.actionPaste.setObjectName(u"actionPaste")
        icon8 = QIcon()
        icon8.addFile(u":/icons/Paste.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPaste.setIcon(icon8)
        self.actionAbout = QAction(MainDisplay)
        self.actionAbout.setObjectName(u"actionAbout")
        icon9 = QIcon()
        icon9.addFile(u":/icons/About.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAbout.setIcon(icon9)
        self.actionAbout_Qt = QAction(MainDisplay)
        self.actionAbout_Qt.setObjectName(u"actionAbout_Qt")
        icon10 = QIcon()
        icon10.addFile(u":/icons/About Qt.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAbout_Qt.setIcon(icon10)
        self.actionOpen = QAction(MainDisplay)
        self.actionOpen.setObjectName(u"actionOpen")
        icon11 = QIcon()
        icon11.addFile(u":/icons/File Open.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionOpen.setIcon(icon11)
        self.actionSave_As = QAction(MainDisplay)
        self.actionSave_As.setObjectName(u"actionSave_As")
        self.centralwidget = QWidget(MainDisplay)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.mdiArea = QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName(u"mdiArea")

        self.verticalLayout.addWidget(self.mdiArea)

        MainDisplay.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainDisplay)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 801, 22))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuWindow = QMenu(self.menubar)
        self.menuWindow.setObjectName(u"menuWindow")
        MainDisplay.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainDisplay)
        self.statusbar.setObjectName(u"statusbar")
        MainDisplay.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainDisplay)
        self.toolBar.setObjectName(u"toolBar")
        MainDisplay.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCut)
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addAction(self.actionPaste)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)

        self.retranslateUi(MainDisplay)

        QMetaObject.connectSlotsByName(MainDisplay)
    # setupUi

    def retranslateUi(self, MainDisplay):
        MainDisplay.setWindowTitle(QCoreApplication.translate("MainDisplay", u"MainWindow", None))
        self.actionNew.setText(QCoreApplication.translate("MainDisplay", u"New", None))
        self.actionSave.setText(QCoreApplication.translate("MainDisplay", u"Save", None))
        self.actionClose.setText(QCoreApplication.translate("MainDisplay", u"Close", None))
        self.actionExit.setText(QCoreApplication.translate("MainDisplay", u"Exit", None))
        self.actionUndo.setText(QCoreApplication.translate("MainDisplay", u"Undo", None))
        self.actionRedo.setText(QCoreApplication.translate("MainDisplay", u"Redo", None))
        self.actionCut.setText(QCoreApplication.translate("MainDisplay", u"Cut", None))
        self.actionCopy.setText(QCoreApplication.translate("MainDisplay", u"Copy", None))
        self.actionPaste.setText(QCoreApplication.translate("MainDisplay", u"Paste", None))
        self.actionAbout.setText(QCoreApplication.translate("MainDisplay", u"About", None))
        self.actionAbout_Qt.setText(QCoreApplication.translate("MainDisplay", u"ABout Qt", None))
        self.actionOpen.setText(QCoreApplication.translate("MainDisplay", u"Open", None))
        self.actionSave_As.setText(QCoreApplication.translate("MainDisplay", u"Save As...", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainDisplay", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainDisplay", u"Edit", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainDisplay", u"Help", None))
        self.menuWindow.setTitle(QCoreApplication.translate("MainDisplay", u"Window", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainDisplay", u"toolBar", None))
    # retranslateUi

